### PR TITLE
Fix/fetch user quizzesfrom db

### LINKED ISSUE #32: Always fetch userQuizzes & replace local data

### PR DESCRIPTION
**Pull request by govind007**
closes #32

### CODE REVIEW

File: src/stores/quizStore.ts [hunk 1]
```diff
@@ -20,11 +20,11 @@ import { GameData } from '../types';
 
 export const getQuizStore = (set: Function, get: Function) => ({
   getQuizzes: async () => {
-    try {
-      const response = await getQuizzes(isGuestUser() ? -1 : get().userData.userId);
+    if (isGuestUser()) {
+      const response = await getQuizzes(-1);
```
Comment (rajatkantinandi) [inline src/stores/quizStore.ts:24]: Do we have an user in our db with -1 userId?
How does this work anyway?

Comment (govind007) [reply src/stores/quizStore.ts:24]: `getQuizzes` fetch data from local storage, for guest user using -1 userId. if not guest user then  fetching data from db

**Review by rajatkantinandi — APPROVED** [review]
