### PR TITLE
fix: Always showing 3 categories after saving 2 categories

### LINKED ISSUE #31: Always showing 3 categories after saving 2 categories

### PR DESCRIPTION
**Pull request by govind007**
- closes #31

### CODE REVIEW

File: src/helpers/dataFormatter.ts [hunk 1]
```diff
@@ -165,11 +165,12 @@ export const formatCategoryInfo = (categories: Category[], categoryIds: (string
 };
 
 export const insertCategoryAndQuestionsData = (quiz) => {
-  if (quiz.categories.length < 3) {
-    quiz.categories = [0, 1, 2].map(
+  if (quiz.categories.length < 2) {
```
Comment (rajatkantinandi) [inline src/helpers/dataFormatter.ts]: Can we add a comment here on why we need to do this?

**Review by rajatkantinandi — APPROVED** [review]
Minor comment

File: src/helpers/dataFormatter.ts [hunk 2]
```diff
@@ -165,11 +165,13 @@ export const formatCategoryInfo = (categories: Category[], categoryIds: (string
 };
 
 export const insertCategoryAndQuestionsData = (quiz) => {
-  if (quiz.categories.length < 3) {
-    quiz.categories = [0, 1, 2].map(
+  // Need atleast 2 categories to show when user refreshes the page after adding less than 2 category
+  if (quiz.categories.length < 2) {
```
Comment (rajatkantinandi) [inline src/helpers/dataFormatter.ts]: Maybe make 2 as a constant as well -> `MIN_NUM_OF_CATEGORIES`

**Review by rajatkantinandi — APPROVED** [review]
